### ISSUE TITLE
If you're still here, I have a question about inflating extracted data from a steg file

### ISSUE THREAD

**Issue by themaddoctor** [zed-0xff/zsteg#1]
One of your samples: ndh2k12_sp113.bmp
```
zsteg -a ndh2k12_sp113.bmp
...
b1,rgb,lsb,yx       .. zlib: data="%PDF-1.4\n%\xC3\xA4\xC3\xBC\xC3\xB6\xC3\x9F\n2 0 obj\n<</Length 3 0 R/Filter/FlateDecode>>\nstream\nx\x9C\x8DT\xC9n\xDB@\f\xBD\xCFW\xF0\x1C \x13\x92\xB3\x03\x86\x80\xC8K\xD1\xDE\\\b\xE8\xA1...", offset=4, size=186                                                                                  
...
```
But I can't figure out how to inflate the data after I have extracted it. I have tried zlib-inflate, pigz, and faking headers for gzip.

Thanks

**Comment by zed-0xff** [comment]
fixed in `zsteg-0.2.1`
now you can extract it with `zsteg samples/ndh2k12_sp113.bmp --extract b1,rgb,lsb,yx,zlib > data.pdf`

**Comment by themaddoctor** [comment]
Thank you. I just upgraded zpng for this, and every time I run it I get
fatal: Not a git repository (or any parent up to mount point /mnt/quadrupole)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Since I am not trying to manage a git repository, but want to use the program on my local system,
how do I get rid of these messages?

**Comment by themaddoctor** [comment]
/usr/lib64/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'rainbow' (~> 2.0.0) - did find: [rainbow-3.0.0] (Gem::LoadError)

**Comment by zed-0xff** [comment]
Hi.
I believe it’s some weird your-system local problem(
I had never seen such messages.
reboot? relogin?
try “which zsteg”
try “irb” and then “require zsteg”
are you using rvm?

вт, 14 янв. 2020 г. в 19:56, themaddoctor <notifications@github.com>:

**Comment by themaddoctor** [comment]
I found the problem with git; there was a problem with rainbow's spec file.
But what about finding rainbow 3 but wanting 2?

**Comment by zed-0xff** [comment]
I think problem is in the new gem dependencies.
I’ll try to fix it tomorrow

вт, 14 янв. 2020 г. в 20:14, themaddoctor <notifications@github.com>:

**Comment by themaddoctor** [comment]
Thanks

**Comment by zed-0xff** [comment]
@themaddoctor please check now

**Comment by themaddoctor** [comment]
All is good. Thank you. Cnacu6o
