### ISSUE TITLE
[Feature Request] Extract all encoutered hidden files

### ISSUE THREAD

**Issue by gmelodie** [zed-0xff/zsteg#10]
I don't think there's currently a way to automatically extract all the hidden files found by `-a`. It'd be nice if we could just:
```
$ zstego -E -a image.png
```

To extract everything hidden on `image.png` to an `output` dir.

**Comment by zed-0xff** [comment]
I see no point in this because on the one hand it's usually 99% of false-positives of some weird formats, and on the other hand often hidden data is not a file but a plain string or "flag".
