### ISSUE TITLE
Getting error messages on installing

### ISSUE THREAD

**Issue by astr1cks** [zed-0xff/zsteg#12]
Can someone please help me out here. I not sure what I'm doing wrong. I installed zsteg into a folder and tried to run it on a png file, but I got these errors.

I had used `gem install zsteg` to install. 

The command I was trying to use was `zsteg filename.png`

------------------------------------------------------------------------------------------------------

`Traceback (most recent call last):
        15: from C:/Ruby27-x64/bin/zsteg:23:in <main>
        14: from C:/Ruby27-x64/bin/zsteg:23:in load
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/bin/zsteg:8:in `<top (required)>'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg.rb:30:in `run'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `run'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each_with_index'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `block in run'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `each'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:162:in `block (2 levels) in run'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:245:in `check'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/checker.rb:68:in `check'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/file_cmd.rb:67:in `start!'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - file -n -b -f - (Errno::ENOENT)
        13: from C:/Ruby27-x64/bin/zsteg:23:in `<main>'
        12: from C:/Ruby27-x64/bin/zsteg:23:in `load'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/bin/zsteg:8:in `<top (required)>'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg.rb:30:in `run'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `run'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each_with_index'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:151:in `each'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `block in run'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:158:in `each'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:162:in `block (2 levels) in run'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/cli/cli.rb:245:in `check'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/checker.rb:119:in `check'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/zsteg-0.2.4/lib/zsteg/checker.rb:119:in `ensure in check'`

**Comment by muellermartin** [comment]
I had this issue when the `file` command was not installed. On Debian this can be resolved with `apt install file` (may also be related to #11)

**Comment by zed-0xff** [comment]
yes, you have to have a file command installed. on windows you can try one from cygwin project
