### ISSUE TITLE
Keep getting "stack level too deep (SystemStackError)" while trying to scan a png.

### ISSUE THREAD

**Issue by real-andree** [zed-0xff/zsteg#30]
Tried as both, root and non-root.
![image](https://user-images.githubusercontent.com/12480931/221664122-73880ded-c75d-4ed4-9fdc-5c8638791556.png)

**Comment by hackipy** [comment]
same issue here

**Comment by 0x157** [comment]
same thing happening to me.

**Comment by bunyamin88** [comment]
yep, same as me. but it is just for a specific file. the other files seem to have normal output

**Comment by 0x157** [comment]
well for some reason after i restarted my machine it worked fine , always works :)

**Comment by zed-0xff** [comment]
is it still an issue? can you share the file producing this behaviour?

**Comment by cardiffcyberinnovationhub** [comment]
Hello @zed-0xff  Hope you are all. I think it is still a issue. Tried to solve PicoCTF 2021 Forensics MilkSlap challenge. File can be downloaded from the below link

http://mercury.picoctf.net:58537/concat_v.png

**Comment by cardiffcyberinnovationhub** [comment]
Hello @zed-0xff Hope you are all. I think it is still a issue. Tried to solve PicoCTF 2021 Forensics MilkSlap challenge. File can be downloaded from the below link

http://mercury.picoctf.net:58537/concat_v.png

**Comment by bitvijays** [comment]
Hello @zed-0xff Hope you are all. I think it is still a issue. Tried to solve PicoCTF 2021 Forensics MilkSlap challenge. File can be downloaded from the below link

http://mercury.picoctf.net:58537/concat_v.png

**Comment by The-Debarghya** [comment]
I guess this isn't an issue particularly with zsteg, instead the image is so big that the recursive stack exceeds the memory limit, and fails.

**Comment by RyanRiz** [comment]
Same here, I'm using Parrot OS and trying to PicoCTF 2021 Forensics MilkSlap challenge too
Here's the log:
`Traceback (most recent call last):
	10237: from /usr/local/bin/zsteg:23:in `<main>'
	10236: from /usr/local/bin/zsteg:23:in `load'
	10235: from /var/lib/gems/2.7.0/gems/zsteg-0.2.13/bin/zsteg:8:in `<top (required)>'
	10234: from /var/lib/gems/2.7.0/gems/zsteg-0.2.13/lib/zsteg.rb:26:in `run'
	10233: from /var/lib/gems/2.7.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `run'
	10232: from /var/lib/gems/2.7.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `each_with_index'
	10231: from /var/lib/gems/2.7.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:161:in `each'
	10230: from /var/lib/gems/2.7.0/gems/zsteg-0.2.13/lib/zsteg/cli/cli.rb:168:in `block in run'
	 ... 10225 levels...
	    4: from /var/lib/gems/2.7.0/gems/zpng-0.4.5/lib/zpng/scan_line/mixins.rb:17:in `prev_scanline_byte'
	    3: from /var/lib/gems/2.7.0/gems/zpng-0.4.5/lib/zpng/scan_line.rb:318:in `decoded_bytes'
	    2: from /var/lib/gems/2.7.0/gems/zpng-0.4.5/lib/zpng/scan_line.rb:318:in `upto'
	    1: from /var/lib/gems/2.7.0/gems/zpng-0.4.5/lib/zpng/scan_line.rb:319:in `block in decoded_bytes'
/var/lib/gems/2.7.0/gems/zpng-0.4.5/lib/zpng/scan_line.rb:369:in `prev_scanline_byte': stack level too deep (SystemStackError)`

I've try reinstall zsteg and iostruct, it still doesn't work

**Comment by fhvirus** [comment]
The issue occurred when I was trying to solve the picoCTF challenge mentioned above. Follwing the instruction given in the link below, I added `export RUBY_THREAD_VM_STACK_SIZE=500000000` to my `.zshrc` to increase ruby's stack size limit and then zsteg worked fine.
https://stackoverflow.com/a/27510458

**Comment by Sul1Mu** [comment]
> The issue occurred when I was trying to solve the picoCTF challenge mentioned above. Follwing the instruction given in the link below, I added `export RUBY_THREAD_VM_STACK_SIZE=500000000` to my `.zshrc` to increase ruby's stack size limit and then zsteg worked fine. https://stackoverflow.com/a/27510458

Thanks! Your idea helped me with resolving that error!

**Comment by zed-0xff** [comment]
btw you don't need to add the env var to any config file, just run it like
```
RUBY_THREAD_VM_STACK_SIZE=500000000 zsteg concat_v.png
```
