### ISSUE TITLE
SyntaxError when trying to run zsteg

### ISSUE THREAD

**Issue by aketon08** [zed-0xff/zsteg#34]
Whenever I run zsteg I get this error
![image](https://github.com/zed-0xff/zsteg/assets/84485391/4666f82b-c4fb-46ce-9f5b-a1275626cb50)

**Comment by dimithras** [comment]
This could be a ruby version problem, 2.5.0 is pretty old, zsteg runs smooth for me on **3.1.2p20**. I might test later on my other machine where I have different ruby versions installed.

**Comment by zed-0xff** [comment]
yes, use newer ruby
