### ISSUE TITLE
Zsteg does not find a full solution

### ISSUE THREAD

**Issue by dimithras** [zed-0xff/zsteg#35]
Following this question on ruSO:
https://ru.stackoverflow.com/questions/1529122/Нужно-вытащить-инфу-из-png

Zsteg worked pretty fine on analyzing the [file](https://github.com/zed-0xff/zsteg/assets/32206956/10c2b0c3-cb95-45e8-98cc-b3d74f5934ea) and brought up a "*near" solution with the desired string and 5 false positives:

``` lang-none
b1,r,lsb,xy         .. text: "P~ZKP:VZ70v0"
b1,r,msb,xy         .. text: "h\\Xjlj~V"
b1,rgb,lsb,xy       .. text: "\ntadluudcl\ndqsushhud\nrmtzamjrgqgb\nowibnivvur\nskbynqx\nfub\nfnsqczqlp\neekr\nzukgr\niqm\niqghhmk\npswzfztfeor\nlhdososrra\nhdajkwyjc\npml\nmcunotfpoog\naenn\nqvfjdebnx\nesdaeenjpp\nzdcygkocgdwa\nhyizstsq\nsbuecriqv\nkov\nkglbfridcq\nhaqfeijqf\nzqusqewebg\naevxiodbztm\njvovealysgs"
b2,g,lsb,xy         .. text: "QAEAQ@AD"
b2,b,lsb,xy         .. text: "PQQT@PAPPTPPP"
b2,b,msb,xy         .. text: "U_]WuW]W"
```

The problem is, this **b1,rgb,lsb,xy** text does not have the hidden message which is "*there is no quest with a portal it's just an excuse*" hidden among a multi-line string with some random chars. However [this site](https://planetcalc.com/9345/) and [another site](https://stylesuxx.github.io/steganography/) worked fine and did yield 62 lines compared to 28 given by *zsteg*. Websites also do provide some binary chars at the end.

Given that, *zsteg* is missing something.

**Comment by zed-0xff** [comment]
just run it with `--limit 0`
