### ISSUE TITLE
--no-color causes uninitialized constant ZSteg::CLI::Cli::Sickill

### ISSUE THREAD

**Issue by d4nyl0** [zed-0xff/zsteg#4]
Hi,

Running zsteg with any option about colors (-C, --color, --no-color) causes
[...].gem/ruby/2.6.0/gems/zsteg-0.1.2/lib/zsteg/cli/cli.rb:127:in `block (2 levels) in run': uninitialized constant ZSteg::CLI::Cli::Sickill (NameError)

**Comment by zed-0xff** [comment]
fixed in 0.2.0
