### ISSUE TITLE
Cross platform incompatibility due to reliance on linux "file" command

### ISSUE THREAD

**Issue by Reelix** [zed-0xff/zsteg#8]
On this line

https://github.com/zed-0xff/zsteg/blob/1d1f79abb997cbad25f0f4ca0664ad0188e47034/lib/zsteg/file_cmd.rb#L67

You rely on the Linux "file" command resulting in cross-platform compatibility issues.

Whilst the help list does have the "--file" parameter to exclude the usage of "file", it does not seem to work, and still attempts to run it.

**Comment by zed-0xff** [comment]
fixed in 0.2.4
